version: "3.7"

services:
  postgres:
    container_name: vogetio-db
    image: postgres:12-alpine
    restart: always
    command: ["-c", "statement_timeout=60000"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vogetio
      POSTGRES_USER: vogetio
      POSTGRES_PASSWORD: vogetio
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/migrations/init/up.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - internal

  app:
    container_name: vogetio-app
    image: node:14-alpine
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
    command: /bin/sh -c "npm run start"
    ports:
      - "3000:3000"
    networks:
      - internal

  server:
    container_name: vogetio-server
    image: node:14-alpine
    volumes:
      - ./server:/home/node/server
    command: /bin/sh -c "npm run dev"
    working_dir: /home/node/server
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://vogetio:vogetio@vogetio-db:5432/vogetio?schema=public"
    networks:
      - internal

  nginx-proxy:
    image: nginx:alpine
    depends_on:
      - app
      - server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    ports:
      - "1234:80"

networks:
  internal:

volumes:
  postgres:
